name: Build Rust package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [ubuntu-latest, x86_64-unknown-linux-gnu],
          [macos-latest, x86_64-apple-darwin]
        ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build package
        run: RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target ${{ matrix.os[1] }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mrml-${{ matrix.os[1] }}
          path: target/release/mrml
